server:
  port: 30000
  address: 0.0.0.0
  servlet:
    context-path: /api/v1/siafms
spring:
  application:
    name: ms-siafms
  profiles:
    active: prod
  banner:
    location: banner/banner.txt
siafms:
  service:
    url: ${SIAFMS_URL}
    ejecutora: ${SIAFMS_EJECUTORA}
    anio: ${SIAFMS_ANIO}
