server:
  port: 7010
  address: 0.0.0.0
  servlet:
    context-path: /api/v1/siafms
spring:
  application:
    name: ms-siafms
  profiles:
    active: prod
  banner:
    location: banner/banner.txt
siafms:
  service:
    url: ${SIAFMS_URL:http://172.16.4.253:59999}
    ejecutora: ${SIAFMS_EJECUTORA:300684}
    anio: ${SIAFMS_ANIO:2025}
